[package]
name = "mark"
version = "0.0.0"
edition = "2021"

[dependencies]
clap = { version = "4.3.19", features = ["derive", "deprecated"] }
image = "0.24.6"
palette = "0.7.2"
rand = { version = "0.8.5", features = ["small_rng"] }
