[package]
name = "mark-bin"
version = { workspace = true }
edition = { workspace = true }

[dependencies]
clap = { workspace = true }
image = { workspace = true, default-features = true }
mark = { workspace = true }
palette = { workspace = true }

[lints]
workspace = true
